# Site settings
title: "Richard Tuttle - Coder, Calligrapher, Educator"
email: "richardtuttle@me.com"
description: "A full-stack engineer with over 20 years of professional experience."
baseurl: "" 
url: "rtuttle.me"
post_url: "/blog"
encoding: UTF-8

twitter_username: "rtuttlecoder"
github_username: "rtuttlecoder"

# Build settings
markdown: kramdown

plugins:
  - jekyll-assets
  - jekyll-redirect-from
  - jekyll-seo-tag
theme: jekyll-theme-hacker