# Site settings
title: "Richard Tuttle - Coder, Educator, Calligrapher"
email: "richardtuttle@me.com"
description: "A full-stack web developer with over 20 years of professional experience."
baseurl: "" 
url: "rtuttlecoder.github.io"
post_url: "/blog"
encoding: UTF-8

twitter_username: "rtuttlecoder"
github_username: "rtuttlecoder"

# Build settings
markdown: kramdown

plugins:
  - jekyll-assets
  - jekyll-redirect-from
  - jekyll-seo-tag